### PR TITLE
Clear "remote:" even where an output line is shorter than it

### PR DESCRIPTION
**Pull request by r7kamura**
In ANSI escape code, the EL code (`CSI n K`) is defined as below:

```
CSI n K : EL – Erase in Line

Erases part of the line. If n is zero (or missing), clear from cursor to the end of the line.
If n is one, clear from cursor to beginning of the line.
If n is two, clear entire line. Cursor position does not change.
```

Here is an examples of `CSI n G` and `CSI n K`.

```
$ echo 'remote: \e[1Gtest'
testte:

$ echo 'remote: \e[1G\e[Ktest'
test
```

Signed-off-by: Ryo Nakamura r7kamura@gmail.com

### CODE REVIEW

**Comment by titanous** [comment]
Thanks! Please add a [DCO sign-off](https://flynn.io/docs/contributing#developers-certificate-of-origin) to the commit.

**Comment by r7kamura** [comment]
Sorry, I missed that! Just rebased and force-pushed e6ec00d7f9b28a4770fa029c7b5ebc2c44635444 :pushpin:

**Comment by titanous** [comment]
Merged, thanks again!

**Comment by r7kamura** [comment]
Thank you for your quick response :yum:

**Pull request merged**
